language: android

android:
  components:
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'

jdk: oraclejdk8

script:
  - ./gradlew assembleDebug testDebugUnitTest
